name: publish npm

on:
  create:
    tags:
      - "v*"

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/"
          scope: "@yalsh"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup protoc
        uses: arduino/setup-protoc@v2.1.0
            
      - name: build scripts
        run: |
          pnpm install
          pnpm run build

      - name: publish
        run: |
          cd dist
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
